dist: trusty
sudo: required
git:
  depth: 10
install:
- SHA=$(git rev-parse  --short HEAD)
-- sudo add-apt-repository ppa:alex-p/tesseract-ocr -y
-- sudo apt-get update -q
-- sudo apt-get install tesseract-ocr -y
-- sudo apt-get install tesseract-ocr-eng -y
-- ls /usr/share/tesseract-ocr/4.00/tessdata
-- which tesseract
-- tesseract -v
-- tesseract --list-langs
before_script:
- mkdir ./out
script:
- ls -l  ./out
after_script:
- cd ./out
- mv ./gt_out.html ./index.html
- git init
- git add --all .
- git commit -m  "${SHA} - Update Github Pages"
- git push  --force https://user:${GH_TOKEN}@github.com/${GITHUB_REPO}.git master:gh-pages
env:
  global:
  - GITHUB_REPO: Shreeshrii/tess4eval_kannada
  - secure: BuKIdTnTTg9HNMSSh8d7Bv9te5bdd7HX7hM6Hf4B3xS7WfCG8KfDaPc2YeENOITuYk/3I9NNgmw+IjGhCs1mWW7HkIpOSCJbcMKp+UrHY+CfuskOEuvQ/yq5f/+WbHRAm3vLCgzC+hoettj+J7XbpiT/vnvWh8pthl/pLZ1Jxpx7owMJCIBxaIjNiv0IsWk9KuG/smF84rbK8JMnPHCRBqZ+ECuD1AzmAXFpH7ilebUKjjQ4I1EOKg9e+yZuQF6dLAxv9JS0E7oaqrsKuArGPfotSR/+W129oDGZ06MxXYnDUu3klPOX7dqppm4xQEJAIuvwZ3CS3KULL5d1MwIB/orsXMRRcez0xtbTkitYSOwyERMmYrai03kV0cWOcxIhf+w/WfSl/ciKmG86Fg0KZCb7kdYzY4bomddEUHSB1t6vTsQpc1Nva8cy0ZvYnjB7TROZCxsv25DqXbdVjbmEAonpH2KFMUnF0J5qO3Eh944sZ7X7kIO8PYNIg4nBOqHLE21a6beNH6aNiaBKnS73fIM5rEC3InmGdmQUt73T+V7iwBew3vuhJejSIE/AMB8CSrv5Evjrv4XJIbXf6gw2T4vs870kgxHdcv5PQm3sF/bgvw3qWWRiSeaxgecSeQHTZGCcdN3BVNu1C1tPnlLynDS0iAc0Jvj3pvaXmdiKSBI=
